services:
  - type: web
    name: bag-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production